name: cooknotes
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.0.1+2
  cupertino_icons: ^1.0.0
  get_it: ^5.0.4
  grouped_buttons: ^1.0.4
  image_picker: ^0.6.7+21
  provider: ^4.3.2+3
  splashscreen: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cooknotes.png
    - assets/cooknotes2.png
    - assets/cook.png
    - assets/article.png
    - assets/logos/google.jpg
    - assets/asampedas.jpg
    - assets/chickenlasagna.jpg
    - assets/ayamgoreng.jpg
    - assets/article1.png
    - assets/siakap.jpg
    - assets/tony.png
    - assets/article2.jpg
    - assets/article1.jpg
    - assets/gordon.jpg
    - assets/pizza.jpg
    - assets/article3.jpg
    - assets/article4.jpg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Lato Black
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
    - family: Lato Bold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
    - family: Montserrat Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Montserrat Black
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
